phpcs:
  stage: test

  image: php:7.4

  before_script:
    - apt update
    - apt install -y libzip-dev

    - pecl install zip
    - docker-php-ext-enable zip

    - php -v

    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "copy('https://composer.github.io/installer.sig', 'composer-setup.checksum');"
    - php -r "if (hash_file('sha384', 'composer-setup.php') !== file_get_contents('composer-setup.checksum')) { echo 'Installer corrupt'; unlink('composer-setup.php'); exit(1); }"
    - php composer-setup.php --install-dir /usr/local/bin --filename=composer
    - php -r "unlink('composer-setup.php');"
    - php -r "unlink('composer-setup.checksum');"

    - composer --version
    - composer update --no-progress --prefer-stable

  script:
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff || true
    - ./vendor/bin/php-cs-fixer fix --dry-run --format=gitlab > gl-code-quality-report.json

  artifacts:
    reports:
      codequality: gl-code-quality-report.json
