workflow:
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - when: always


variables:
  DOCKER_REGISTRY: wearestancer
  PHP_VERSION: "7.4"


phpcs:
  stage: test

  image: ${DOCKER_REGISTRY}/php:${PHP_VERSION}

  before_script:
    - php -v
    - composer --version

    - composer update --no-progress --prefer-stable

  script:
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff || true
    - ./vendor/bin/php-cs-fixer fix --dry-run --format=gitlab > gl-code-quality-report.json

  artifacts:
    reports:
      codequality: gl-code-quality-report.json
