workflow:
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - when: always

variables:
  DOCKER_REGISTRY: wearestancer
  PHP_VERSION: "8.1"
  PS_VERSION: "8.0"


.base-php:
  image: ${DOCKER_REGISTRY}/php:${PHP_VERSION}
  stage: test
  before_script:
    - php --version
    - composer --version
    - composer install


.base-prestashop:
  image: ${DOCKER_REGISTRY}/prestashop:${PS_VERSION}-php${PHP_VERSION}
  stage: deploy
  before_script:
    - php --version
    - composer --version
    - pnpm --version

    # Apply git filters
    - sh scripts/git-filters.sh 1

    - pnpm install


Create archive:
  extends:
    - .base-prestashop

  script:
    - pnpm run build:archive
    - export ZIP_NAME="ps-${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"
    - echo "${ZIP_NAME}"
    - mv stancer*.zip "${ZIP_NAME}.zip"

  artifacts:
    paths:
      - '*.zip'


phpcs:
  extends:
    - .base-php

  script:
    - composer run phpcs || true
    - composer run phpcs -- --format=gitlab > gl-code-quality-report.json

  artifacts:
    reports:
      codequality: gl-code-quality-report.json


phpstan:
  extends:
    - .base-php

  script:
    - composer run phpstan || true
    - composer run phpstan -- --error-format=gitlab > gl-static-analysis-report.json

  artifacts:
    reports:
      codequality: gl-static-analysis-report.json
