phpcs:
  stage: test

  image: php:7.4

  before_script:
    - apt update
    - apt install -y libzip-dev

    - pecl install zip
    - docker-php-ext-enable zip

    - php -v

    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "copy('https://composer.github.io/installer.sig', 'composer-setup.checksum');"
    - php -r "if (hash_file('sha384', 'composer-setup.php') !== file_get_contents('composer-setup.checksum')) { echo 'Installer corrupt'; unlink('composer-setup.php'); exit(1); }"
    - php composer-setup.php --install-dir /usr/local/bin --filename=composer
    - php -r "unlink('composer-setup.php');"
    - php -r "unlink('composer-setup.checksum');"

    - composer --version
    - composer update --no-progress --prefer-stable

  script:
    - ./vendor/bin/phpcs || true
    - ./vendor/bin/phpcs --report=junit --report-file=phpcs.junit.xml

  artifacts:
    reports:
      junit: phpcs.junit.xml

zip:
  stage: deploy

  before_script:
    - composer --version
    - node -v
    - npm -v
    - pnpm -v
    - composer install --no-dev
    - pnpm install

  script:
    - pnpm run create-assets
    - pnpm run translate
    - pnpm run populate
    - pnpm run version
    - pnpm run archive

  artifacts:
    paths:
      - stancer.zip

  only:
    - tags
    - master
