
extends:
  - stylelint-config-concentric-order
  - stylelint-config-sass-guidelines
  - stylelint-config-standard-scss


rules:
  at-rule-empty-line-before:
    - always
    - except:
        - blockless-after-same-name-blockless
        - first-nested
      ignore:
        - after-comment
        - blockless-after-same-name-blockless

  at-rule-no-unknown: null

  declaration-block-no-redundant-longhand-properties: null

  declaration-no-important: true

  max-nesting-depth: 5

  no-empty-source: null

  number-leading-zero: never

  order/order:
    - custom-properties
    - dollar-variables
    - type: at-rule
      name: extend
    - type: at-rule
      name: include
    - declarations
    - type: at-rule
      name: supports
    - rules
    - type: at-rule
      name: media
    - type: at-rule
      name: include
      parameter: only-on-very-small-screen
    - type: at-rule
      name: include
      parameter: only-on-small-screen
    - type: at-rule
      name: include
      parameter: only-on-medium-screen
    - type: at-rule
      name: include
      parameter: only-on-large-screen
    - type: at-rule
      name: keyframes

  order/properties-alphabetical-order: null

  scss/at-else-closing-brace-newline-after: null

  scss/at-else-closing-brace-space-after: null

  scss/at-else-empty-line-before: null

  scss/at-function-parentheses-space-before: never

  scss/at-if-closing-brace-newline-after: null

  scss/at-if-closing-brace-space-after: null

  scss/at-if-no-null: true

  scss/at-mixin-argumentless-call-parentheses: never

  scss/at-mixin-parentheses-space-before: never

  scss/at-rule-conditional-no-parentheses: true

  scss/no-duplicate-mixins: true

  scss/no-global-function-names: true

  scss/selector-nest-combinators: always

  scss/selector-no-redundant-nesting-selector: null

  selector-class-pattern:
    - '^[a-z0-9]+(?:-[a-z0-9]+)*(?:_{2}[a-z0-9]+(?:-[a-z0-9]+)*){0,2}(?:-{2}[a-z0-9]+(?:-[a-z0-9]+)*)?$'
    - resolveNestedSelectors: true

  selector-max-compound-selectors: 5

  string-quotes: single

  value-keyword-case:
    - lower
    - camelCaseSvgKeywords: true
