#! /bin/bash

set -eu -o pipefail

web_dir="/var/www/html"
plugin_dir="${web_dir}/modules/stancer"
devcontainer_dir="${plugin_dir}/.devcontainer"


DB_PASSWD="${DB_PASSWD:-root}"
DB_PORT="${DB_PORT:-3306}"
DB_SERVER="${DB_SERVER:-mysql}"
DB_USER="${DB_USER:-root}"


# Configure git
git --git-dir="${plugin_dir}/.git" config --global --add safe.directory "$plugin_dir"
sh "${plugin_dir}/scripts/git-filters.sh"

# Install dependencies
composer install --working-dir="${plugin_dir}"
pnpm config set store-dir "${HOME}/.cache/pnpm"
pnpm install --dir "${plugin_dir}"

# Prepare assets
pnpm run --dir "${plugin_dir}" create-assets
pnpm run --dir "${plugin_dir}" translate


# Get Caddy root CA
curl http://caddy:2019/pki/ca/local/certificates -so "${devcontainer_dir}/root-ca.crt"


if [ -d "${web_dir}/install" ]; then
  # Prepare the database
  mysql -h $DB_SERVER -P $DB_PORT -u $DB_USER -p$DB_PASSWD -ANe "CREATE DATABASE IF NOT EXISTS $DB_NAME;"

  # Install PrestaShop
  ps-install

fi

# Create an user
php "${plugin_dir}/.devcontainer/scripts/create-user.php"


# Remove the pretty URL options (it breaks products images, we did not configure Caddy to handle it)
mysql -h $DB_SERVER -P $DB_PORT -u $DB_USER -p$DB_PASSWD -AN <<-SQL
  UPDATE \`${DB_NAME}\`.\`${DB_PREFIX}configuration\`
  SET value = NULL
  WHERE name = 'PS_REWRITING_SETTINGS';
SQL

# Remove Preston (the onboarding only)
mysql -h $DB_SERVER -P $DB_PORT -u $DB_USER -p$DB_PASSWD -AN <<-SQL
  INSERT INTO \`${DB_NAME}\`.\`${DB_PREFIX}configuration\` (name, value, date_add, date_upd)
  VALUES ("ONBOARDINGV2_SHUT_DOWN", 1, NOW(), NOW());
SQL


# Cache clearing
php -d memory_limit=-1 "${web_dir}/app/console" cache:clear -q


# Output
protocol="http://"

if [ "$PS_ENABLE_SSL" = 1 ]; then
  protocol="https://"
fi

underline=$(tput smul)
nounderline=$(tput rmul)
bold=$(tput bold)
normal=$(tput sgr0)
red="\033[38;5;9m"

echo ""
echo "${underline}${bold}Default settings${normal}${nounderline}"
echo ""
echo "Website accessible at:      ${protocol}${PS_DOMAIN}"
echo "Admin panel accessible at:  ${protocol}${PS_DOMAIN}/ps-admin"
echo ""
echo "Admin mail:                 ${ADMIN_MAIL}"
echo "Admin password:             ${ADMIN_PASSWD}"
echo ""
echo "Test user mail:             shop-user@stancer.com"
echo "Test password:              shop-user"
echo ""
echo "Webmail:                    ${protocol}${PS_DOMAIN/prestashop/mailtrap}"
echo "Webmail login:              mailtrap"
echo "Webmail password:           mailtrap"
echo ""
echo -e "${red}The module is currently uninstalled, but the file are at the good place"
echo "just install the module from the marketplace and it will install this codebase. "
echo -e "${bold}Stancer API keys cannot be properly setup as we cannot install the module in cli.${normal}"
echo ""
